name: portal
description: A Flutter plugin to build widgets out of the current tree. Similar to React Portals.
version: 1.0.0+2
authors:
  - Rhodes Davis Jr. <rody.davis.jr@gmail.com>
  - Rive <info@rive.app>
homepage: https://github.com/rive-app/portal

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
